.PHONY: clean All

All:
	@echo "----------Building project:[ IMS - Debug ]----------"
	@"$(MAKE)" -f  "IMS.mk"
clean:
	@echo "----------Cleaning project:[ IMS - Debug ]----------"
	@"$(MAKE)" -f  "IMS.mk" clean
