.PHONY: clean All

All:
	@echo "----------Building project:[ DNS - Debug ]----------"
	@cd "/home/pdancak/school/MrPain_T/ISA/DNS" && "$(MAKE)" -f  "DNS.mk"
clean:
	@echo "----------Cleaning project:[ DNS - Debug ]----------"
	@cd "/home/pdancak/school/MrPain_T/ISA/DNS" && "$(MAKE)" -f  "DNS.mk" clean
